version: "1.0"
services:
  h2db:
    image: oscarfonts/h2:latest
    container_name: my-h2db
    ports:
      - "1521:1521"  # TCP 포트
      - "81:81"      # H2 웹 콘솔
    environment:
      H2_OPTIONS: "-ifNotExists -tcp -tcpAllowOthers -web -webAllowOthers"
    volumes:
      - h2-data:/opt/h2-data

volumes:
  h2-data: