spring:
  docker:
    compose:
      enabled: true
  jpa:
    hibernate:
      ddl-auto: create
  datasource:
    url: jdbc:h2:tcp://localhost:1521/./test
    username: sa
    password:
    driver-class-name: org.h2.Driver

server:
  error:
    whitelabel:
      enabled: false

